CREATE TABLE doctors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    specialty VARCHAR(80) NOT NULL,
    phone VARCHAR(30),
    email VARCHAR(120)
);

CREATE TABLE patients (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    document_number VARCHAR(30) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    email VARCHAR(120) NOT NULL,
    birth_date DATE,
    CONSTRAINT uk_patient_document UNIQUE (document_number)
);

CREATE TABLE appointments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    doctor_id BIGINT NOT NULL,
    appointment_date_time TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL,
    cancellation_date_time TIMESTAMP,
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_appointments_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT ck_appointments_status CHECK (status IN ('PROGRAMADA', 'CANCELADA', 'ATENDIDA'))
);

CREATE INDEX idx_appointments_doctor_status_datetime ON appointments (doctor_id, status, appointment_date_time);
CREATE INDEX idx_appointments_patient_status_datetime ON appointments (patient_id, status, appointment_date_time);
CREATE INDEX idx_appointments_datetime ON appointments (appointment_date_time);

CREATE TABLE penalties (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    appointment_id BIGINT NOT NULL,
    penalty_date_time TIMESTAMP NOT NULL,
    reason VARCHAR(200) NOT NULL,
    CONSTRAINT fk_penalties_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT fk_penalties_appointment FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);

CREATE INDEX idx_penalties_patient_datetime ON penalties (patient_id, penalty_date_time);

CREATE TABLE doctor_slot_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doctor_id BIGINT NOT NULL,
    appointment_date_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_doctor_slot_locks_doctor FOREIGN KEY (doctor_id) REFERENCES doctors(id),
    CONSTRAINT uk_doctor_slot_lock UNIQUE (doctor_id, appointment_date_time)
);

CREATE TABLE patient_slot_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id BIGINT NOT NULL,
    appointment_date_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_patient_slot_locks_patient FOREIGN KEY (patient_id) REFERENCES patients(id),
    CONSTRAINT uk_patient_slot_lock UNIQUE (patient_id, appointment_date_time)
);
